// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ruidgfgymrnvlaabwhtt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1aWRnZmd5bXJudmxhYWJ3aHR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMjg1OTEsImV4cCI6MjA3MDgwNDU5MX0.EsxqP98oOd7Kw8kZJ89BzbDyvSurYedVXvm7kH4enKw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});